name: Windows build (MSVC)

on:
  push:
    branches:
      - main
  pull_request:
     branches:
       - main

jobs:
  build:
    name: meson MSVC
    runs-on: windows-latest

    steps:
    - name: Fetch Sources
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: pip install meson ninja

    - name: Prepare MSVC
      uses: bus1/cabuild/action/msdevshell@v1
      with:
        architecture: x64

    - name: Prepare Build
      run: |
        python scripts/install_wraps.py
        meson setup build

    - name: Run Build
      run: meson compile -v -C build

    - name: Run Test Suite
      run: meson test -v -C build
